version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: dockerhub-flask_live_app:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=mysql://root:Taft#2021@flask_db:3306/sailing_club_database
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Taft#2021
      - MYSQL_DATABASE=sailing_club_database
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata: {}
